In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Datasets/smoking.csv")
df

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,81.3,1.2,1.0,1.0,1.0,...,12.9,1.0,0.7,18.0,19.0,27.0,Y,0,Y,0
1,1,F,40,160,60,81.0,0.8,0.6,1.0,1.0,...,12.7,1.0,0.6,22.0,19.0,18.0,Y,0,Y,0
2,2,M,55,170,60,80.0,0.8,0.8,1.0,1.0,...,15.8,1.0,1.0,21.0,16.0,22.0,Y,0,N,1
3,3,M,40,165,70,88.0,1.5,1.5,1.0,1.0,...,14.7,1.0,1.0,19.0,26.0,18.0,Y,0,Y,0
4,4,F,40,155,60,86.0,1.0,1.0,1.0,1.0,...,12.5,1.0,0.6,16.0,14.0,22.0,Y,0,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55687,55676,F,40,170,65,75.0,0.9,0.9,1.0,1.0,...,12.3,1.0,0.6,14.0,7.0,10.0,Y,1,Y,0
55688,55681,F,45,160,50,70.0,1.2,1.2,1.0,1.0,...,14.0,1.0,0.9,20.0,12.0,14.0,Y,0,Y,0
55689,55683,F,55,160,50,68.5,1.0,1.2,1.0,1.0,...,12.4,1.0,0.5,17.0,11.0,12.0,Y,0,N,0
55690,55684,M,60,165,60,78.0,0.8,1.0,1.0,1.0,...,14.4,1.0,0.7,20.0,19.0,18.0,Y,0,N,0
55691,55691,M,55,160,65,85.0,0.9,0.7,1.0,1.0,...,15.0,1.0,0.8,26.0,29.0,41.0,Y,0,Y,1

In [2]:
df.shape

(55692, 27)

In [3]:
data = df.iloc[:400]

In [4]:
data.shape

(400, 27)

In [5]:
data

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,81.3,1.2,1.0,1.0,1.0,...,12.9,1.0,0.7,18.0,19.0,27.0,Y,0,Y,0
1,1,F,40,160,60,81.0,0.8,0.6,1.0,1.0,...,12.7,1.0,0.6,22.0,19.0,18.0,Y,0,Y,0
2,2,M,55,170,60,80.0,0.8,0.8,1.0,1.0,...,15.8,1.0,1.0,21.0,16.0,22.0,Y,0,N,1
3,3,M,40,165,70,88.0,1.5,1.5,1.0,1.0,...,14.7,1.0,1.0,19.0,26.0,18.0,Y,0,Y,0
4,4,F,40,155,60,86.0,1.0,1.0,1.0,1.0,...,12.5,1.0,0.6,16.0,14.0,22.0,Y,0,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,499,F,40,165,55,76.0,1.5,1.5,1.0,1.0,...,13.1,1.0,1.0,16.0,12.0,12.0,Y,0,Y,0
396,500,M,30,165,75,82.4,1.2,1.2,1.0,1.0,...,14.9,1.0,0.8,25.0,34.0,46.0,Y,0,N,1
397,501,F,40,155,65,83.2,1.0,1.0,1.0,1.0,...,9.3,1.0,0.7,19.0,17.0,17.0,Y,0,N,0
398,502,F,50,155,55,73.4,1.5,1.0,1.0,1.0,...,12.9,1.0,0.7,21.0,14.0,14.0,Y,0,N,0
399,503,F,40,165,65,79.0,0.4,1.0,1.0,1.0,...,14.0,2.0,0.6,22.0,12.0,15.0,Y,0,Y,0

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   400 non-null    int64
 1   gender               400 non-null    str
 2   age                  400 non-null    int64
 3   height(cm)           400 non-null    int64
 4   weight(kg)           400 non-null    int64
 5   waist(cm)            400 non-null    float64
 6   eyesight(left)       400 non-null    float64
 7   eyesight(right)      400 non-null    float64
 8   hearing(left)        400 non-null    float64
 9   hearing(right)       400 non-null    float64
 10  systolic             400 non-null    float64
 11  relaxation           400 non-null    float64
 12  fasting blood sugar  400 non-null    float64
 13  Cholesterol          400 non-null    float64
 14  triglyceride         400 non-null    float64
 15  HDL                  400 non-null    float64
 16  LDL                  400 non-null    float64
 17  hemoglobin           400 non-null    float64
 18  Urine protein        400 non-null    float64
 19  serum creatinine     400 non-null    float64
 20  AST                  400 non-null    float64
 21  ALT                  400 non-null    float64
 22  Gtp                  400 non-null    float64
 23  oral                 400 non-null    str
 24  dental caries        400 non-null    int64
 25  tartar               400 non-null    str
 26  smoking              400 non-null    int64
dtypes: float64(18), int64(6), str(3)
memory usage: 84.5 KB

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['tartar'] = le.fit_transform(data[['tartar']])
data['gender'] = le.fit_transform(data[['gender']])
data['oral'] = le.fit_transform(data[['oral']])

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   400 non-null    int64
 1   gender               400 non-null    int64
 2   age                  400 non-null    int64
 3   height(cm)           400 non-null    int64
 4   weight(kg)           400 non-null    int64
 5   waist(cm)            400 non-null    float64
 6   eyesight(left)       400 non-null    float64
 7   eyesight(right)      400 non-null    float64
 8   hearing(left)        400 non-null    float64
 9   hearing(right)       400 non-null    float64
 10  systolic             400 non-null    float64
 11  relaxation           400 non-null    float64
 12  fasting blood sugar  400 non-null    float64
 13  Cholesterol          400 non-null    float64
 14  triglyceride         400 non-null    float64
 15  HDL                  400 non-null    float64
 16  LDL                  400 non-null    float64
 17  hemoglobin           400 non-null    float64
 18  Urine protein        400 non-null    float64
 19  serum creatinine     400 non-null    float64
 20  AST                  400 non-null    float64
 21  ALT                  400 non-null    float64
 22  Gtp                  400 non-null    float64
 23  oral                 400 non-null    int64
 24  dental caries        400 non-null    int64
 25  tartar               400 non-null    int64
 26  smoking              400 non-null    int64
dtypes: float64(18), int64(9)
memory usage: 84.5 KB

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [8]:
X = data.drop(['ID','smoking'],axis=1)
y= data['smoking']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
accuracy_score(y_pred,y_test)

0.8

In [11]:
from sklearn.model_selection import GridSearchCV

In [12]:
forest_params =  [{'max_depth':list(range(10,15)),'max_features': list (range(0,14)) }]

clf = GridSearchCV(rfc,forest_params,cv=10,scoring = 'accuracy')
clf.fit(X_train,y_train)

print(clf.best_params_)
print(clf.best_score_)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
50 fits failed out of a total of 700.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 0 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [     nan 0.696875 0.70625  0.7125   0.703125 0.69375  0.709375 0.696875
 0.7      0.715625 0.70625  0.7125   0.715625 0.709375      nan 0.675
 0.690625 0.7      0.703125 0.7      0.70625  0.70625  0.715625 0.70625
 0.7      0.7125   0.690625 0.709375      nan 0.7      0.6875   0.7
 0.715625 0.7      0.7      0.7      0.7      0.71875  0.69375  0.696875
 0.684375 0.69375       nan 0.6875   0.6875   0.725    0.696875 0.70625
 0.68125  0.715625 0.68125  0.709375 0.71875  0.703125 0.703125 0.7125
      nan 0.7      0.696875 0.7      0.7125   0.7125   0.696875 0.703125
 0.721875 0.696875 0.696875 0.709375 0.696875 0.684375]
  warnings.warn(

{'max_depth': 13, 'max_features': 3}
0.725

In [13]:
y_pred = clf.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.775